package ObjectInterface.ReaderModule;


/**
* ObjectInterface/ReaderModule/ReaderInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Reader.idl
* Wednesday, November 6, 2019 11:16:36 PM ICT
*/

public interface ReaderInterface extends ReaderInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ReaderInterface
