package ObjectInterface.ReaderModule;


/**
* ObjectInterface/ReaderModule/ReaderInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Reader.idl
* Thursday, November 7, 2019 10:59:28 PM ICT
*/

public interface ReaderInterface extends ReaderInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ReaderInterface
