package ObjectInterface.ReaderModule;


/**
* ObjectInterface/ReaderModule/ReaderInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Reader.idl
* Wednesday, November 6, 2019 11:16:36 PM ICT
*/

public interface ReaderInterfaceOperations 
{
  int id ();
  void id (int newId);
  String readerName ();
  void readerName (String newReaderName);
  String birthday ();
  void birthday (String newBirthday);
  String address ();
  void address (String newAddress);
  String phoneNumber ();
  void phoneNumber (String newPhoneNumber);
  String email ();
  void email (String newEmail);
  ObjectInterface.ReaderModule.Reader getSingle (int id);
  ObjectInterface.ReaderModule.Reader[] list ();
} // interface ReaderInterfaceOperations
