package ObjectInterface.ReaderModule;


/**
* ObjectInterface/ReaderModule/ReadersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Reader.idl
* Wednesday, November 6, 2019 11:16:36 PM ICT
*/

public final class ReadersHolder implements org.omg.CORBA.portable.Streamable
{
  public ObjectInterface.ReaderModule.Reader value[] = null;

  public ReadersHolder ()
  {
  }

  public ReadersHolder (ObjectInterface.ReaderModule.Reader[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ObjectInterface.ReaderModule.ReadersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ObjectInterface.ReaderModule.ReadersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ObjectInterface.ReaderModule.ReadersHelper.type ();
  }

}
