package ObjectInterface.ReaderModule;


/**
* ObjectInterface/ReaderModule/ReaderInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Reader.idl
* Friday, November 15, 2019 3:32:31 PM ICT
*/

abstract public class ReaderInterfaceHelper
{
  private static String  _id = "IDL:ObjectInterface/ReaderModule/ReaderInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, ObjectInterface.ReaderModule.ReaderInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ObjectInterface.ReaderModule.ReaderInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ObjectInterface.ReaderModule.ReaderInterfaceHelper.id (), "ReaderInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ObjectInterface.ReaderModule.ReaderInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ReaderInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ObjectInterface.ReaderModule.ReaderInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ObjectInterface.ReaderModule.ReaderInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ObjectInterface.ReaderModule.ReaderInterface)
      return (ObjectInterface.ReaderModule.ReaderInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ObjectInterface.ReaderModule._ReaderInterfaceStub stub = new ObjectInterface.ReaderModule._ReaderInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ObjectInterface.ReaderModule.ReaderInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ObjectInterface.ReaderModule.ReaderInterface)
      return (ObjectInterface.ReaderModule.ReaderInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ObjectInterface.ReaderModule._ReaderInterfaceStub stub = new ObjectInterface.ReaderModule._ReaderInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
