package ObjectInterface.ReaderModule;


/**
* ObjectInterface/ReaderModule/Reader.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Reader.idl
* Wednesday, November 6, 2019 11:16:36 PM ICT
*/

public final class Reader implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String readerName = null;
  public String birthday = null;
  public String address = null;
  public String phoneNumber = null;
  public String email = null;

  public Reader ()
  {
  } // ctor

  public Reader (int _id, String _readerName, String _birthday, String _address, String _phoneNumber, String _email)
  {
    id = _id;
    readerName = _readerName;
    birthday = _birthday;
    address = _address;
    phoneNumber = _phoneNumber;
    email = _email;
  } // ctor

} // class Reader
