package ObjectInterface.ReaderModule;


/**
* ObjectInterface/ReaderModule/ReaderInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Reader.idl
* Thursday, November 7, 2019 10:59:28 PM ICT
*/

public abstract class ReaderInterfacePOA extends org.omg.PortableServer.Servant
 implements ObjectInterface.ReaderModule.ReaderInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_id", new java.lang.Integer (0));
    _methods.put ("_set_id", new java.lang.Integer (1));
    _methods.put ("_get_readerName", new java.lang.Integer (2));
    _methods.put ("_set_readerName", new java.lang.Integer (3));
    _methods.put ("_get_birthday", new java.lang.Integer (4));
    _methods.put ("_set_birthday", new java.lang.Integer (5));
    _methods.put ("_get_address", new java.lang.Integer (6));
    _methods.put ("_set_address", new java.lang.Integer (7));
    _methods.put ("_get_phoneNumber", new java.lang.Integer (8));
    _methods.put ("_set_phoneNumber", new java.lang.Integer (9));
    _methods.put ("_get_email", new java.lang.Integer (10));
    _methods.put ("_set_email", new java.lang.Integer (11));
    _methods.put ("getSingle", new java.lang.Integer (12));
    _methods.put ("list", new java.lang.Integer (13));
    _methods.put ("add", new java.lang.Integer (14));
    _methods.put ("delete", new java.lang.Integer (15));
    _methods.put ("update", new java.lang.Integer (16));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ObjectInterface/ReaderModule/ReaderInterface/_get_id
       {
         int $result = (int)0;
         $result = this.id ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // ObjectInterface/ReaderModule/ReaderInterface/_set_id
       {
         int newId = in.read_long ();
         this.id (newId);
         out = $rh.createReply();
         break;
       }

       case 2:  // ObjectInterface/ReaderModule/ReaderInterface/_get_readerName
       {
         String $result = null;
         $result = this.readerName ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // ObjectInterface/ReaderModule/ReaderInterface/_set_readerName
       {
         String newReaderName = in.read_string ();
         this.readerName (newReaderName);
         out = $rh.createReply();
         break;
       }

       case 4:  // ObjectInterface/ReaderModule/ReaderInterface/_get_birthday
       {
         String $result = null;
         $result = this.birthday ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // ObjectInterface/ReaderModule/ReaderInterface/_set_birthday
       {
         String newBirthday = in.read_string ();
         this.birthday (newBirthday);
         out = $rh.createReply();
         break;
       }

       case 6:  // ObjectInterface/ReaderModule/ReaderInterface/_get_address
       {
         String $result = null;
         $result = this.address ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // ObjectInterface/ReaderModule/ReaderInterface/_set_address
       {
         String newAddress = in.read_string ();
         this.address (newAddress);
         out = $rh.createReply();
         break;
       }

       case 8:  // ObjectInterface/ReaderModule/ReaderInterface/_get_phoneNumber
       {
         String $result = null;
         $result = this.phoneNumber ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 9:  // ObjectInterface/ReaderModule/ReaderInterface/_set_phoneNumber
       {
         String newPhoneNumber = in.read_string ();
         this.phoneNumber (newPhoneNumber);
         out = $rh.createReply();
         break;
       }

       case 10:  // ObjectInterface/ReaderModule/ReaderInterface/_get_email
       {
         String $result = null;
         $result = this.email ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 11:  // ObjectInterface/ReaderModule/ReaderInterface/_set_email
       {
         String newEmail = in.read_string ();
         this.email (newEmail);
         out = $rh.createReply();
         break;
       }

       case 12:  // ObjectInterface/ReaderModule/ReaderInterface/getSingle
       {
         int id = in.read_long ();
         ObjectInterface.ReaderModule.Reader $result = null;
         $result = this.getSingle (id);
         out = $rh.createReply();
         ObjectInterface.ReaderModule.ReaderHelper.write (out, $result);
         break;
       }

       case 13:  // ObjectInterface/ReaderModule/ReaderInterface/list
       {
         ObjectInterface.ReaderModule.Reader $result[] = null;
         $result = this.list ();
         out = $rh.createReply();
         ObjectInterface.ReaderModule.ReadersHelper.write (out, $result);
         break;
       }

       case 14:  // ObjectInterface/ReaderModule/ReaderInterface/add
       {
         ObjectInterface.ReaderModule.Reader o = ObjectInterface.ReaderModule.ReaderHelper.read (in);
         int $result = (int)0;
         $result = this.add (o);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 15:  // ObjectInterface/ReaderModule/ReaderInterface/delete
       {
         ObjectInterface.ReaderModule.Reader o = ObjectInterface.ReaderModule.ReaderHelper.read (in);
         int $result = (int)0;
         $result = this.delete (o);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 16:  // ObjectInterface/ReaderModule/ReaderInterface/update
       {
         ObjectInterface.ReaderModule.Reader o = ObjectInterface.ReaderModule.ReaderHelper.read (in);
         int $result = (int)0;
         $result = this.update (o);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ObjectInterface/ReaderModule/ReaderInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ReaderInterface _this() 
  {
    return ReaderInterfaceHelper.narrow(
    super._this_object());
  }

  public ReaderInterface _this(org.omg.CORBA.ORB orb) 
  {
    return ReaderInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class ReaderInterfacePOA
