package ObjectInterface.ReaderModule;


/**
* ObjectInterface/ReaderModule/ReaderInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Reader.idl
* Friday, November 15, 2019 3:32:31 PM ICT
*/

public interface ReaderInterface extends ReaderInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ReaderInterface
