package MyAccount;


/**
* MyAccount/Account.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MyAccount/Account.idl
* Tuesday, November 5, 2019 2:49:18 PM ICT
*/

public interface Account extends AccountOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Account
