package MyAccount;


/**
* MyAccount/AccountPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from MyAccount/Account.idl
* Tuesday, November 5, 2019 2:49:18 PM ICT
*/

public abstract class AccountPOA extends org.omg.PortableServer.Servant
 implements MyAccount.AccountOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_accountNo", new java.lang.Integer (0));
    _methods.put ("_set_accountNo", new java.lang.Integer (1));
    _methods.put ("desposit", new java.lang.Integer (2));
    _methods.put ("withdraw", new java.lang.Integer (3));
    _methods.put ("reportBalance", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MyAccount/Account/_get_accountNo
       {
         int $result = (int)0;
         $result = this.accountNo ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // MyAccount/Account/_set_accountNo
       {
         int newAccountNo = in.read_long ();
         this.accountNo (newAccountNo);
         out = $rh.createReply();
         break;
       }

       case 2:  // MyAccount/Account/desposit
       {
         double amount = in.read_double ();
         this.desposit (amount);
         out = $rh.createReply();
         break;
       }

       case 3:  // MyAccount/Account/withdraw
       {
         double amount = in.read_double ();
         this.withdraw (amount);
         out = $rh.createReply();
         break;
       }

       case 4:  // MyAccount/Account/reportBalance
       {
         double $result = (double)0;
         $result = this.reportBalance ();
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MyAccount/Account:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Account _this() 
  {
    return AccountHelper.narrow(
    super._this_object());
  }

  public Account _this(org.omg.CORBA.ORB orb) 
  {
    return AccountHelper.narrow(
    super._this_object(orb));
  }


} // class AccountPOA
