package ObjectInterface.Test;


/**
* ObjectInterface/Test/TestInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Test.idl
* Wednesday, November 6, 2019 7:11:31 AM ICT
*/

public interface TestInterfaceOperations 
{
  boolean test ();
} // interface TestInterfaceOperations
