package ObjectInterface.Test;


/**
* ObjectInterface/Test/TestInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Test.idl
* Wednesday, November 6, 2019 7:11:31 AM ICT
*/

public interface TestInterface extends TestInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TestInterface
