package ObjectInterface.Test;


/**
* ObjectInterface/Test/TestInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interface/Test.idl
* Tuesday, November 5, 2019 4:34:51 PM ICT
*/

public interface TestInterface extends TestInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface TestInterface
