package ObjectInterface.Test;


/**
* ObjectInterface/Test/TestInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Test.idl
* Tuesday, November 5, 2019 11:15:28 PM ICT
*/

public interface TestInterfaceOperations 
{
  boolean test ();
} // interface TestInterfaceOperations
