package ObjectInterface.UserModule;


/**
* ObjectInterface/UserModule/UserInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/User.idl
* Friday, November 15, 2019 3:32:30 PM ICT
*/

public interface UserInterface extends UserInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface UserInterface
