package ObjectInterface.UserModule;


/**
* ObjectInterface/UserModule/UserInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/User.idl
* Wednesday, November 6, 2019 7:11:30 AM ICT
*/

public interface UserInterface extends UserInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface UserInterface
