package ObjectInterface.UserModule;


/**
* ObjectInterface/UserModule/User.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/User.idl
* Friday, November 15, 2019 3:32:30 PM ICT
*/

public final class User implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String name = null;
  public String username = null;
  public String type = null;
  public String password = null;

  public User ()
  {
  } // ctor

  public User (int _id, String _name, String _username, String _type, String _password)
  {
    id = _id;
    name = _name;
    username = _username;
    type = _type;
    password = _password;
  } // ctor

} // class User
