package ObjectInterface.UserModule;


/**
* ObjectInterface/UserModule/UsersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/User.idl
* Thursday, November 7, 2019 10:59:27 PM ICT
*/

public final class UsersHolder implements org.omg.CORBA.portable.Streamable
{
  public ObjectInterface.UserModule.User value[] = null;

  public UsersHolder ()
  {
  }

  public UsersHolder (ObjectInterface.UserModule.User[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ObjectInterface.UserModule.UsersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ObjectInterface.UserModule.UsersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ObjectInterface.UserModule.UsersHelper.type ();
  }

}
