package ObjectInterface.UserModule;


/**
* ObjectInterface/UserModule/UserInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/User.idl
* Thursday, November 7, 2019 11:32:24 PM ICT
*/

public interface UserInterface extends UserInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface UserInterface
