package ObjectInterface.BillModule;


/**
* ObjectInterface/BillModule/BillsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Bill.idl
* Friday, November 8, 2019 12:56:36 PM ICT
*/

public final class BillsHolder implements org.omg.CORBA.portable.Streamable
{
  public ObjectInterface.BillModule.Bill value[] = null;

  public BillsHolder ()
  {
  }

  public BillsHolder (ObjectInterface.BillModule.Bill[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ObjectInterface.BillModule.BillsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ObjectInterface.BillModule.BillsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ObjectInterface.BillModule.BillsHelper.type ();
  }

}
