package ObjectInterface.BillModule;


/**
* ObjectInterface/BillModule/BillInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Bill.idl
* Thursday, November 7, 2019 11:32:28 PM ICT
*/

public interface BillInterface extends BillInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BillInterface
