package ObjectInterface.BillModule;


/**
* ObjectInterface/BillModule/BillsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Bill.idl
* Thursday, November 7, 2019 11:32:28 PM ICT
*/

abstract public class BillsHelper
{
  private static String  _id = "IDL:ObjectInterface/BillModule/Bills:1.0";

  public static void insert (org.omg.CORBA.Any a, ObjectInterface.BillModule.Bill[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ObjectInterface.BillModule.Bill[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = ObjectInterface.BillModule.BillHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (ObjectInterface.BillModule.BillsHelper.id (), "Bills", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ObjectInterface.BillModule.Bill[] read (org.omg.CORBA.portable.InputStream istream)
  {
    ObjectInterface.BillModule.Bill value[] = null;
    int _len0 = istream.read_long ();
    value = new ObjectInterface.BillModule.Bill[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = ObjectInterface.BillModule.BillHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ObjectInterface.BillModule.Bill[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      ObjectInterface.BillModule.BillHelper.write (ostream, value[_i0]);
  }

}
