package ObjectInterface.BillModule;


/**
* ObjectInterface/BillModule/BillInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Bill.idl
* Wednesday, November 6, 2019 11:16:38 PM ICT
*/

public interface BillInterfaceOperations 
{
  int id ();
  void id (int newId);
  int status ();
  void status (int newStatus);
  int readerID ();
  void readerID (int newReaderID);
  String createdAt ();
  void createdAt (String newCreatedAt);
  String deadline ();
  void deadline (String newDeadline);
  ObjectInterface.BillModule.Bill getSingle (int id);
  ObjectInterface.BillModule.Bill[] list (int readerID);
} // interface BillInterfaceOperations
