package ObjectInterface.BillModule;


/**
* ObjectInterface/BillModule/BillInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Bill.idl
* Friday, November 8, 2019 12:56:36 PM ICT
*/

public interface BillInterface extends BillInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BillInterface
