package ObjectInterface.BillModule;


/**
* ObjectInterface/BillModule/Bill.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Bill.idl
* Thursday, November 7, 2019 10:59:30 PM ICT
*/

public final class Bill implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public int status = (int)0;
  public int readerID = (int)0;
  public String createdAt = null;
  public String deadline = null;

  public Bill ()
  {
  } // ctor

  public Bill (int _id, int _status, int _readerID, String _createdAt, String _deadline)
  {
    id = _id;
    status = _status;
    readerID = _readerID;
    createdAt = _createdAt;
    deadline = _deadline;
  } // ctor

} // class Bill
