package ObjectInterface.BillModule;

/**
* ObjectInterface/BillModule/BillInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Bill.idl
* Thursday, November 7, 2019 10:59:30 PM ICT
*/

public final class BillInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public ObjectInterface.BillModule.BillInterface value = null;

  public BillInterfaceHolder ()
  {
  }

  public BillInterfaceHolder (ObjectInterface.BillModule.BillInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ObjectInterface.BillModule.BillInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ObjectInterface.BillModule.BillInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ObjectInterface.BillModule.BillInterfaceHelper.type ();
  }

}
