package ObjectInterface.BillModule;


/**
* ObjectInterface/BillModule/BillInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Bill.idl
* Thursday, November 7, 2019 10:59:30 PM ICT
*/

abstract public class BillInterfaceHelper
{
  private static String  _id = "IDL:ObjectInterface/BillModule/BillInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, ObjectInterface.BillModule.BillInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ObjectInterface.BillModule.BillInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ObjectInterface.BillModule.BillInterfaceHelper.id (), "BillInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ObjectInterface.BillModule.BillInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_BillInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ObjectInterface.BillModule.BillInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ObjectInterface.BillModule.BillInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ObjectInterface.BillModule.BillInterface)
      return (ObjectInterface.BillModule.BillInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ObjectInterface.BillModule._BillInterfaceStub stub = new ObjectInterface.BillModule._BillInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ObjectInterface.BillModule.BillInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ObjectInterface.BillModule.BillInterface)
      return (ObjectInterface.BillModule.BillInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ObjectInterface.BillModule._BillInterfaceStub stub = new ObjectInterface.BillModule._BillInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
