package ObjectInterface.BillModule;

/**
* ObjectInterface/BillModule/BillHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Bill.idl
* Friday, November 8, 2019 12:56:36 PM ICT
*/

public final class BillHolder implements org.omg.CORBA.portable.Streamable
{
  public ObjectInterface.BillModule.Bill value = null;

  public BillHolder ()
  {
  }

  public BillHolder (ObjectInterface.BillModule.Bill initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ObjectInterface.BillModule.BillHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ObjectInterface.BillModule.BillHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ObjectInterface.BillModule.BillHelper.type ();
  }

}
