package ObjectInterface.CategoryModule;

/**
* ObjectInterface/CategoryModule/CategoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Category.idl
* Wednesday, November 6, 2019 11:16:35 PM ICT
*/

public final class CategoryHolder implements org.omg.CORBA.portable.Streamable
{
  public ObjectInterface.CategoryModule.Category value = null;

  public CategoryHolder ()
  {
  }

  public CategoryHolder (ObjectInterface.CategoryModule.Category initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ObjectInterface.CategoryModule.CategoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ObjectInterface.CategoryModule.CategoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ObjectInterface.CategoryModule.CategoryHelper.type ();
  }

}
