package ObjectInterface.CategoryModule;


/**
* ObjectInterface/CategoryModule/CategoryInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Category.idl
* Thursday, November 7, 2019 10:59:28 PM ICT
*/

public interface CategoryInterface extends CategoryInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CategoryInterface
