package ObjectInterface.CategoryModule;


/**
* ObjectInterface/CategoryModule/CategoryInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Category.idl
* Wednesday, November 6, 2019 11:16:36 PM ICT
*/

public interface CategoryInterface extends CategoryInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CategoryInterface
