package ObjectInterface.CategoryModule;


/**
* ObjectInterface/CategoryModule/CategoryInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Category.idl
* Friday, November 15, 2019 3:32:30 PM ICT
*/

public interface CategoryInterface extends CategoryInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface CategoryInterface
