package ObjectInterface.CategoryModule;


/**
* ObjectInterface/CategoryModule/CategoryInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Category.idl
* Wednesday, November 6, 2019 11:16:36 PM ICT
*/

public interface CategoryInterfaceOperations 
{
  int id ();
  void id (int newId);
  String categoryName ();
  void categoryName (String newCategoryName);
  ObjectInterface.CategoryModule.Category getSingle (int id);
  ObjectInterface.CategoryModule.Category[] list ();
} // interface CategoryInterfaceOperations
