module ObjectInterface {
    module BillDetailModule {
        struct BillDetail{
            long billID, bookID, borrowAmount, status;
        };

        interface BillDetailInterface {
            attribute long billID, bookID, borrowAmount, status;
            BillDetail getSingle(in long id);
        };
    };
};