module ObjectInterface {
    module BillModule {
        struct Bill{
            long id, status, readerID;
            string createdAt, deadline, readerName, bookName;
        };

        typedef sequence <Bill> Bills;
        typedef sequence<long> longs;

        interface BillInterface {
            attribute long id, status, readerID;
            attribute string createdAt, deadline, readerName, bookName;
            Bill getSingle(in long id);
            Bills list(in long readerID);
            void borrowBook(in long readerID, in longs bookIDs, in string deadline);
            boolean payBook(in longs ids, in long billID);
        };
    };
};