module ObjectInterface {
    module BookModule {
        struct Book{
            long id, inventory, borrowAmount, categoryID, currentBorrow;
            string bookName, publishingCompany, createdAt, categoryName, author;
        };

        struct Author {
            string name;
        };

        struct NXB {
            string name;
        };

        typedef sequence <Book> Books;
        typedef sequence <Author> Authors;
        typedef sequence <NXB> NXBs;

        interface BookInterface {
            attribute long id, inventory, borrowAmount, categoryID, currentBorrow;
            attribute string bookName, publishingCompany, createdAt, categoryName, author;
            Book getSingle(in long id);
            Books list();
            Books listByCatID(in long id);
            Books listByBillID(in long id);
            long add(in Book o);
            long delete(in Book o);
            long update(in Book o);
            Authors listAuthor();
            NXBs listNXB();
        };
    };
};