module ObjectInterface {
    module UserModule {
        struct User{
            long id;
            string name, username, type, password;
        };

        typedef sequence <User> Users;

        interface UserInterface {
            attribute long id;
            attribute string name, username, password, type;
            User login(in string username, in string password);
            User getSingle(in long id);
            Users list();
            long add(in User u);
            long delete(in User u);
            long update(in User u);
        };
    };
};