package ObjectInterface.User;


/**
* ObjectInterface/User/UserInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Interface/User.idl
* Tuesday, November 5, 2019 4:34:50 PM ICT
*/

public interface UserInterface extends UserInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface UserInterface
