package ObjectInterface.BillDetailModule;


/**
* ObjectInterface/BillDetailModule/BillDetailInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/BillDetail.idl
* Thursday, November 7, 2019 10:59:30 PM ICT
*/

public abstract class BillDetailInterfacePOA extends org.omg.PortableServer.Servant
 implements ObjectInterface.BillDetailModule.BillDetailInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_billID", new java.lang.Integer (0));
    _methods.put ("_set_billID", new java.lang.Integer (1));
    _methods.put ("_get_bookID", new java.lang.Integer (2));
    _methods.put ("_set_bookID", new java.lang.Integer (3));
    _methods.put ("_get_borrowAmount", new java.lang.Integer (4));
    _methods.put ("_set_borrowAmount", new java.lang.Integer (5));
    _methods.put ("getSingle", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ObjectInterface/BillDetailModule/BillDetailInterface/_get_billID
       {
         int $result = (int)0;
         $result = this.billID ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // ObjectInterface/BillDetailModule/BillDetailInterface/_set_billID
       {
         int newBillID = in.read_long ();
         this.billID (newBillID);
         out = $rh.createReply();
         break;
       }

       case 2:  // ObjectInterface/BillDetailModule/BillDetailInterface/_get_bookID
       {
         int $result = (int)0;
         $result = this.bookID ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // ObjectInterface/BillDetailModule/BillDetailInterface/_set_bookID
       {
         int newBookID = in.read_long ();
         this.bookID (newBookID);
         out = $rh.createReply();
         break;
       }

       case 4:  // ObjectInterface/BillDetailModule/BillDetailInterface/_get_borrowAmount
       {
         int $result = (int)0;
         $result = this.borrowAmount ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 5:  // ObjectInterface/BillDetailModule/BillDetailInterface/_set_borrowAmount
       {
         int newBorrowAmount = in.read_long ();
         this.borrowAmount (newBorrowAmount);
         out = $rh.createReply();
         break;
       }

       case 6:  // ObjectInterface/BillDetailModule/BillDetailInterface/getSingle
       {
         int id = in.read_long ();
         ObjectInterface.BillDetailModule.BillDetail $result = null;
         $result = this.getSingle (id);
         out = $rh.createReply();
         ObjectInterface.BillDetailModule.BillDetailHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ObjectInterface/BillDetailModule/BillDetailInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public BillDetailInterface _this() 
  {
    return BillDetailInterfaceHelper.narrow(
    super._this_object());
  }

  public BillDetailInterface _this(org.omg.CORBA.ORB orb) 
  {
    return BillDetailInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class BillDetailInterfacePOA
