package ObjectInterface.BillDetailModule;


/**
* ObjectInterface/BillDetailModule/BillDetail.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/BillDetail.idl
* Thursday, November 7, 2019 10:59:30 PM ICT
*/

public final class BillDetail implements org.omg.CORBA.portable.IDLEntity
{
  public int billID = (int)0;
  public int bookID = (int)0;
  public int borrowAmount = (int)0;

  public BillDetail ()
  {
  } // ctor

  public BillDetail (int _billID, int _bookID, int _borrowAmount)
  {
    billID = _billID;
    bookID = _bookID;
    borrowAmount = _borrowAmount;
  } // ctor

} // class BillDetail
