package ObjectInterface.BillDetailModule;


/**
* ObjectInterface/BillDetailModule/BillDetailInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/BillDetail.idl
* Wednesday, November 6, 2019 11:16:38 PM ICT
*/

public interface BillDetailInterfaceOperations 
{
  int billID ();
  void billID (int newBillID);
  int bookID ();
  void bookID (int newBookID);
  int borrowAmount ();
  void borrowAmount (int newBorrowAmount);
  ObjectInterface.BillDetailModule.BillDetail getSingle (int id);
} // interface BillDetailInterfaceOperations
