package ObjectInterface.BillDetailModule;

/**
* ObjectInterface/BillDetailModule/BillDetailHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/BillDetail.idl
* Friday, November 8, 2019 12:56:37 PM ICT
*/

public final class BillDetailHolder implements org.omg.CORBA.portable.Streamable
{
  public ObjectInterface.BillDetailModule.BillDetail value = null;

  public BillDetailHolder ()
  {
  }

  public BillDetailHolder (ObjectInterface.BillDetailModule.BillDetail initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ObjectInterface.BillDetailModule.BillDetailHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ObjectInterface.BillDetailModule.BillDetailHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ObjectInterface.BillDetailModule.BillDetailHelper.type ();
  }

}
