package ObjectInterface.BillDetailModule;


/**
* ObjectInterface/BillDetailModule/BillDetailInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/BillDetail.idl
* Thursday, November 7, 2019 10:59:30 PM ICT
*/

public interface BillDetailInterface extends BillDetailInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BillDetailInterface
