package ObjectInterface.BookModule;


/**
* ObjectInterface/BookModule/AuthorsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Book.idl
* Friday, November 8, 2019 12:56:36 PM ICT
*/

public final class AuthorsHolder implements org.omg.CORBA.portable.Streamable
{
  public ObjectInterface.BookModule.Author value[] = null;

  public AuthorsHolder ()
  {
  }

  public AuthorsHolder (ObjectInterface.BookModule.Author[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ObjectInterface.BookModule.AuthorsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ObjectInterface.BookModule.AuthorsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ObjectInterface.BookModule.AuthorsHelper.type ();
  }

}
