package ObjectInterface.BookModule;


/**
* ObjectInterface/BookModule/Author.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Book.idl
* Thursday, November 7, 2019 11:32:27 PM ICT
*/

public final class Author implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;

  public Author ()
  {
  } // ctor

  public Author (String _name)
  {
    name = _name;
  } // ctor

} // class Author
