package ObjectInterface.BookModule;


/**
* ObjectInterface/BookModule/BookInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Book.idl
* Thursday, December 5, 2019 9:25:23 PM ICT
*/

public interface BookInterfaceOperations 
{
  int id ();
  void id (int newId);
  int inventory ();
  void inventory (int newInventory);
  int borrowAmount ();
  void borrowAmount (int newBorrowAmount);
  int categoryID ();
  void categoryID (int newCategoryID);
  int currentBorrow ();
  void currentBorrow (int newCurrentBorrow);
  String bookName ();
  void bookName (String newBookName);
  String publishingCompany ();
  void publishingCompany (String newPublishingCompany);
  String createdAt ();
  void createdAt (String newCreatedAt);
  String categoryName ();
  void categoryName (String newCategoryName);
  String author ();
  void author (String newAuthor);
  ObjectInterface.BookModule.Book getSingle (int id);
  ObjectInterface.BookModule.Book[] list ();
  ObjectInterface.BookModule.Book[] listByCatID (int id);
  ObjectInterface.BookModule.Book[] listByBillID (int id);
  int add (ObjectInterface.BookModule.Book o);
  int delete (ObjectInterface.BookModule.Book o);
  int update (ObjectInterface.BookModule.Book o);
  ObjectInterface.BookModule.Author[] listAuthor ();
  ObjectInterface.BookModule.NXB[] listNXB ();
} // interface BookInterfaceOperations
