package ObjectInterface.BookModule;


/**
* ObjectInterface/BookModule/BookInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Book.idl
* Thursday, December 5, 2019 9:25:23 PM ICT
*/

public interface BookInterface extends BookInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BookInterface
