package ObjectInterface.BookModule;


/**
* ObjectInterface/BookModule/BookInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Book.idl
* Wednesday, November 6, 2019 11:16:37 PM ICT
*/

public interface BookInterfaceOperations 
{
  int id ();
  void id (int newId);
  int inventory ();
  void inventory (int newInventory);
  int borrowAmount ();
  void borrowAmount (int newBorrowAmount);
  int categoryID ();
  void categoryID (int newCategoryID);
  String bookName ();
  void bookName (String newBookName);
  String publishingCompany ();
  void publishingCompany (String newPublishingCompany);
  String createdAt ();
  void createdAt (String newCreatedAt);
  String categoryName ();
  void categoryName (String newCategoryName);
  ObjectInterface.BookModule.Book getSingle (int id);
  ObjectInterface.BookModule.Book[] list ();
} // interface BookInterfaceOperations
