package ObjectInterface.BookModule;


/**
* ObjectInterface/BookModule/BookInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Book.idl
* Friday, November 8, 2019 12:56:36 PM ICT
*/

public interface BookInterface extends BookInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BookInterface
