package ObjectInterface.BookModule;


/**
* ObjectInterface/BookModule/NXB.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Book.idl
* Friday, November 15, 2019 3:32:31 PM ICT
*/

public final class NXB implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;

  public NXB ()
  {
  } // ctor

  public NXB (String _name)
  {
    name = _name;
  } // ctor

} // class NXB
