package ObjectInterface.BookModule;

/**
* ObjectInterface/BookModule/NXBHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Module/Book.idl
* Friday, November 15, 2019 3:32:31 PM ICT
*/

public final class NXBHolder implements org.omg.CORBA.portable.Streamable
{
  public ObjectInterface.BookModule.NXB value = null;

  public NXBHolder ()
  {
  }

  public NXBHolder (ObjectInterface.BookModule.NXB initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ObjectInterface.BookModule.NXBHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ObjectInterface.BookModule.NXBHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ObjectInterface.BookModule.NXBHelper.type ();
  }

}
