package TempConvertApp;


/**
* TempConvertApp/Convert.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TempConvertApp/Convert.idl
* Tuesday, November 5, 2019 2:49:33 PM ICT
*/

public interface Convert extends ConvertOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Convert
