package TempConvertApp;


/**
* TempConvertApp/ConvertPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from TempConvertApp/Convert.idl
* Tuesday, November 5, 2019 2:49:33 PM ICT
*/

public abstract class ConvertPOA extends org.omg.PortableServer.Servant
 implements TempConvertApp.ConvertOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("cToF", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // TempConvertApp/Convert/cToF
       {
         double c = in.read_double ();
         double $result = (double)0;
         $result = this.cToF (c);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:TempConvertApp/Convert:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Convert _this() 
  {
    return ConvertHelper.narrow(
    super._this_object());
  }

  public Convert _this(org.omg.CORBA.ORB orb) 
  {
    return ConvertHelper.narrow(
    super._this_object(orb));
  }


} // class ConvertPOA
